Mh auth pundit
mauriushill/industrial-auth-1 pull request #2
Opened 2024-03-11 21:30 UTC by mauriushill

2024-03-13 20:22 UTC, evilla092 requested changes
In the user profile I noticed I can still see other people's pending followers. I believe it should only show up for the users own profile.

also you might want to allow an owner of a post to delete comments under it even if they ddidn't create the comment. Other than that everything else looks great.

2024-03-13 21:34 UTC, evilla092 requested changes
Everything works perfectly. I would just recommend hiding the edit link from your comment view if you're not the comment.author.

2024-03-14 15:46 UTC, thierrychau approved these changes
Few minor comments. Otherwise:
- tested and working (except for the fact that I can delete other users' comments)
- verify_authorized and verify_policy_scoped are present
- authorize is being called in all controllers (except like but it's ok since it's not fully implemented)
- there is a policy for all controllers (except like but it's ok since it's not fully implemented). 

Great work Maurius!

2024-03-14 15:46 UTC, thierrychau commented on app/controllers/photos_controller.rb
>    before_action :ensure_current_user_is_owner, only:[:destroy, :update, :edit]
Can be removed once Pundit is completely implemented

2024-03-14 15:46 UTC, thierrychau commented on app/controllers/photos_controller.rb
>    before_action :ensure_current_user_is_owner, only:[:destroy, :update, :edit]
Still here! But it's ok.

2024-03-14 15:46 UTC, thierrychau commented on app/policies/comment_policy.rb
> +      user == comment.owner
`.owner` is not a valid method. I think because of this I'm able to delete anyone's comment

2024-03-14 15:46 UTC, thierrychau commented on app/policies/user_policy.rb
Great job!

2024-03-14 15:46 UTC, thierrychau commented on app/views/comments/_comment.html.erb
> +    <% if current_user == comment.author %>
Use `if policy(comment).edit?` instead for better code organization

2024-03-18 14:35 UTC, evilla092 approved these changes
Great corrections. Keep it up!

2024-03-20 20:25 UTC, lateefidris reviewed
Everything looks to be working fine!

2024-03-28 17:57 UTC, merged